version: '3.8'

services:
  # MongoDB with authentication and initialization
  mongodb:
    image: mongo:7.0
    container_name: smartcity-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: SmartCityParking
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - smartcity-network

  # MongoDB management UI
  mongo-express:
    image: mongo-express:1.0.0
    container_name: smartcity-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongodb
    networks:
      - smartcity-network

  # Redis
  redis:
    image: redis:latest
    container_name: smartcity-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - smartcity-network

  # Redis management UI
  redis-insight:
    image: redis/redisinsight:latest
    container_name: smartcity-redis-insight
    restart: always
    ports:
      - "8001:8001"
    networks:
      - smartcity-network

  # RabbitMQ with management plugin
  rabbitmq:
    image: rabbitmq:3-management
    container_name: smartcity-rabbitmq
    restart: always
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - smartcity-network

volumes:
  mongodb_data:
    driver: local

networks:
  smartcity-network:
    driver: bridge